substitutions:
  devicename: test1
  devicename_upper: Test 1

esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s

esp32_touch:
  setup_mode: false

# Enable logging
#logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${devicename_upper} Hotspot
    password: "YkWrDjdKBYmS"

captive_portal:

ota:
  password: !secret esphome_ota_password

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Sensors
binary_sensor:
  - platform: gpio
    id: test_btn
    name: ${devicename_upper} Taster 1
    pin:
      number: 2
      inverted: true
    on_multi_click:
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.2s
        - ON for at most 0.5s
        - OFF for at most 0.2s
        - ON for at most 0.5s
        - OFF for at least 0.5s
      then:
        - logger.log: "Tripple Clicked - Lights on 100"
        - light.turn_on:
            id: test_pwm
            brightness: 100%
    - timing:
        - ON for at most 0.5s
        - OFF for at most 0.2s
        - ON for at least 0.5s
      then:
        - logger.log: "Double Clicked and holding - Dimm Lights up"
        - while:
            condition:
              binary_sensor.is_on: test_btn
            then:
              - light.dim_relative:
                  id: test_pwm
                  relative_brightness: 0.3%
                  transition_length: 0.01s
              - delay: 0.01s
    - timing:
        - ON for at least 0.5s
      then:
        - logger.log: "Single Clicked and holding - Dimm Lights down"
        - while:
            condition:
              binary_sensor.is_on: test_btn
            then:
              - light.dim_relative:
                  id: test_pwm
                  relative_brightness: -0.3%
                  transition_length: 0.01s
              - delay: 0.01s
    - timing:
        - ON for at most 1s
        - OFF for at least 0.5s
      then:
        - logger.log: "Single Short Clicked - Toggle Lights"
        - light.toggle:
            id: test_pwm
            transition_length: 3s

# Lights
light:
  - platform: monochromatic
    id: test_pwm
    name: ${devicename_upper} PWM Light
    output: test_pwm_output
    effects:
      - pulse:
          name: Slow Pulse
          transition_length: 5s
          update_interval: 5s
      - flicker:
          name: Flicker Effect
          alpha: 95%
          intensity: 1.5%
      - strobe:
          name: Strobe Effect
          colors:
            - state: True
              brightness: 100%
              duration: 2s
            - state: True
              brightness: 30%
              duration: 500ms

# Output (with conversion)
output:
  - platform: template
    id: test_pwm_output
    type: float
    write_action:
      - lambda: 'id(test_pwm_output_gpio).set_level(state == 0 ? 0 : 0.023 + state * (1 - 0.023));'
  - platform: ledc
    id: test_pwm_output_gpio
    pin: 5